# Generated by Django 5.1.6 on 2025-03-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('selected_country', models.CharField(max_length=100)),
                ('selected_language', models.CharField(max_length=50)),
                ('selected_currency', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=50)),
                ('swift_bic', models.CharField(max_length=50)),
                ('bank_location', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=100)),
                ('billing_address', models.TextField()),
                ('billing_country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShopApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_xml', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='api.shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SupplierApplication',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.shop'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
