# Generated by Django 5.1.6 on 2025-03-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
