# Generated by Django 5.1.6 on 2025-03-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shop_user_alter_customer_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='verifications/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
        ),
    ]
