# Generated by Django 5.1.6 on 2025-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shopverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='shop_pictures/'),
        ),
        migrations.DeleteModel(
            name='ShopVerification',
        ),
    ]
