# Generated by Django 5.1.6 on 2025-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shop_profile_picture_delete_shopverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
