# Generated by Django 5.1.6 on 2025-03-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('shipped_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_confirmations', to='api.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
            options={
                'unique_together': {('order', 'shop')},
            },
        ),
    ]
